import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./style.scss";

import Header from "./components/Header";
import Footer from "./components/Footer";

import { Noto_Sans } from "next/font/google";
import { ThemeProvider } from "@mui/material";
import { theme } from "./mui/theme";

import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { cookies } from "next/headers";
import AccessibilityMenu from "./components/AccessibilityMenu";

type Props = {
  children: React.ReactNode;
  params: { locale: string };
};

const noto = Noto_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "mygov",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children
}: Props) {
  let messages;

  const store = await cookies();
  const locale = store.get("locale")?.value || "az";

  try {
    messages = (await import(`../components/messages/${locale}.json`)).default;
  } catch {
    console.error("Locale not found:", locale);
 }

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider theme={theme}>
            <AccessibilityMenu/>
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
          
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
